# NUMPY

NumPy is a powerful numerical computing library for Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. 

#### you can import NumPy in your Python script or interactive session

In [53]:
# Import NumPy

import numpy as np

#### you can check NumPy Version

NumPy version is the version number of the NumPy library being used. This version number provides information about the specific release of NumPy, including bug fixes, feature enhancements, and other changes that have been made in that version.

In [54]:
# Checking NumPy Version

print(np.__version__)

1.26.4


### NumPy Array

Arrays: NumPy provides the numpy.ndarray data structure, commonly known as arrays, which are similar to Python lists but more efficient for numerical computations. Arrays can have any number of dimensions and can hold elements of the same data type.

In the context of NumPy arrays, the terms "dimension," "row," and "element" refer to the main components of an array.

- Dimension: Dimension refers to the number of axes or levels that an array has. For example, a one-dimensional array has one dimension (single axis), a two-dimensional array has two dimensions (horizontal and vertical axes), and so on. The number of dimensions of an array can be viewed using the ndim attribute of the array.

- Row: In the context of two-dimensional arrays or higher, a row refers to a sequence of data that is horizontally located within the array. A row in a two-dimensional array consists of a set of data with the same dimension, for example, in a two-dimensional array, each row consists of the same number of elements. The number of rows in an array can be viewed using the shape attribute of the array.

- Element: An element is an individual value contained within an array. Each element in an array has a specific location or index that indicates its position within the array. These elements can be accessed using indexing or slicing. For example, in a two-dimensional array, each element is a single value located at the intersection of a row and column.

##### NumPy array 1D

In [12]:
# Creating a NumPy array 1D

arr = np.array ([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [15]:
arr = np.array ([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
my_list = np.array (['apple, banana, cherry, date, elderberry'])
print(my_list)

['apple, banana, cherry, date, elderberry']


In [17]:
my_list = np.array (['apple, banana, cherry, date, elderberry'])
print(my_list)
print(type(my_list))

['apple, banana, cherry, date, elderberry']
<class 'numpy.ndarray'>


##### NumPy array 2D

In [18]:
# Creating a NumPy array 2D

arr = np.array ([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
arr = np.array ([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [20]:
my_list = np.array ([['apple, banana, cherry'], ['orange, date, elderberry']])
print(my_list)
print(type(my_list))

[['apple, banana, cherry']
 ['orange, date, elderberry']]
<class 'numpy.ndarray'>


##### NumPy array 3D

In [22]:
# Creating a NumPy array 3D

arr = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [23]:
my_list = np.array ([[['apple, banana'], ['cherry, orange'], ['date, elderberry']]])
print(my_list)
print(type(my_list))

[[['apple, banana']
  ['cherry, orange']
  ['date, elderberry']]]
<class 'numpy.ndarray'>


##### Check how many dimensions the arrays have

In [24]:
a = np.array (50)
b = np.array (['apple, banana, cherry, date, elderberry'])
c = np.array ([['apple, banana, cherry'], ['orange, date, elderberry']])
d = np.array ([[['apple, banana'], ['cherry, orange'], ['date, elderberry']]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


##### Create an array with 5 dimensions and verify that is has 5 dimensions

In [25]:
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print('number of dimension:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


In [50]:
arr_x = np.array([11, 12, 13, 14], ndmin = 6)
print(arr_x)
print('number of dimension:', arr_x.ndim)

[[[[[[11 12 13 14]]]]]]
number of dimension: 6


##### Reshape from one dimension to another dimension

In [52]:
arr_x = np.array([11, 12, 13, 14], ndmin = 6)
print(arr_x)
print('number of dimension:', arr_x.ndim)
print(arr_x[0])

[[[[[[11 12 13 14]]]]]]
number of dimension: 6
[[[[[11 12 13 14]]]]]


##### Get the first element from the following array

In [28]:
arr_x = np.array([11, 12, 13, 14])
print(arr_x[0])

11


##### Get the second element from the following array

In [29]:
arr_x = np.array([11, 12, 13, 14])
print(arr_x[1])

12


##### Get the third and fourth elements from the following array and add them

In [30]:
arr_x = np.array([11, 12, 13, 14])
print(arr_x[2] + arr_x[3])

27


##### Access the element on the first row, second column

In [31]:
arr_x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print('2nd element on 1st row:', arr_x[0, 1])

2nd element on 1st row: 12


##### Access the element on the 2nd row, 5th column

In [33]:
arr_x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print('5th element on 2nd row:', arr_x[1, 4]) #[row, element]

5th element on 2nd row: 20


##### Access the 3rd element of the 2nd array of the 1st array

In [40]:
arr_x = np.array([[[11, 12, 13], [14, 15, 16]], [[17, 18, 19], [20, 21, 22]]])
print(arr_x[1, 0, 2]) #[dim, row, element]

19


##### Example 4D

In [47]:
arr_x = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]])
print(arr_x[0, 1, 2]) #[dim, row, element]

6


_- dim 0 = [[1, 2, 3], [4, 5, 6]]_
_- row 1 = [4, 5, 6]_
_- element 2 = 6_

##### Print the last element from the 2nd dimensions

In [56]:
arr_x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print('Last element from 2nd dimensions:', arr_x[1, -1])

Last element from 2nd dimensions: 20


The provided code snippet initializes a NumPy array arr_x with dimensions 2x5 (2 rows and 5 columns). Here's the explanation of the code and its output:

- arr_x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]): This line creates a NumPy array with 2 rows and 5 columns. Each row contains a sequence of integers from 11 to 15 for the first row and from 16 to 20 for the second row.

- print('Last element from 2nd dimensions:', arr_x[1, -1]): This line prints the last element from the second dimension (dimension index 1) of the array. In NumPy indexing, -1 refers to the last element, -2 refers to the second last element, and so on. Since we're accessing the second row (index 1) and the last element of that row, arr_x[1, -1] accesses the last element of the second row and prints its value.